import * as vscode from 'vscode';
import * as net from 'net';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import { generateSetupScript, generateRollbackScript } from './remoteSetup';

const execAsync = promisify(exec);

let debugChannel: vscode.OutputChannel;

function debug(message: string): void {
	const timestamp = new Date().toISOString();
	const location = isRunningLocally() ? '[LOCAL]' : '[REMOTE]';
	debugChannel?.appendLine(`${timestamp} ${location} ${message}`);
}

function isRunningLocally(): boolean {
	return !vscode.env.remoteName;
}

async function checkPortAvailable(host: string, port: number): Promise<boolean> {
	return new Promise((resolve) => {
		const socket = new net.Socket();
		socket.setTimeout(1000);
		socket.on('connect', () => { socket.destroy(); resolve(true); });
		socket.on('timeout', () => { socket.destroy(); resolve(false); });
		socket.on('error', () => { socket.destroy(); resolve(false); });
		socket.connect(port, host);
	});
}

/**
 * Get path to SSH config directory based on platform
 */
function getSSHDir(): string {
	return path.join(os.homedir(), '.ssh');
}

/**
 * Get path to our custom SSH config file
 */
function getSSHConfigAntigravityPath(): string {
	return path.join(getSSHDir(), 'config.antigravity');
}



/**
 * Generate the SSH config content with RemoteForward
 */
async function generateSSHConfigContent(port: number, originalConfigContent: string | null): Promise<string> {
	const lines = [
		'# Auto-generated by Antigravity Proxy extension',
		'# Do not edit manually - changes will be overwritten',
		'',
		'Host *',
		`    RemoteForward ${port} 127.0.0.1:${port}`,
		'    ExitOnForwardFailure no',
		'    VisualHostKey no',
		'',
	];

	if (originalConfigContent) {
		lines.push('# --- Original SSH config content below ---');
		lines.push(originalConfigContent);
	}

	return lines.join('\n');
}

/**
 * Update the SSH config file and VS Code settings
 */
async function updateSSHConfigFile(port: number, enable: boolean): Promise<void> {
	const configPath = getSSHConfigAntigravityPath();

	try {
		if (enable) {
			// Ensure .ssh directory exists
			await fs.mkdir(getSSHDir(), { recursive: true });

			// Read original config content if it exists
			let originalConfigContent: string | null = null;
			try {
				const originalPath = path.join(getSSHDir(), 'config');
				originalConfigContent = await fs.readFile(originalPath, 'utf-8');
			} catch {
				// Original config doesn't exist, that's fine
			}

			// Generate new config content
			const content = await generateSSHConfigContent(port, originalConfigContent);

			// Check if config already has the same content
			let existingContent = '';
			try {
				existingContent = await fs.readFile(configPath, 'utf-8');
			} catch {
				// File doesn't exist, that's fine
			}

			if (existingContent === content) {
				debug('SSH config already up to date, skipping');
				return;
			}

			// Write new config
			await fs.writeFile(configPath, content, { encoding: 'utf-8' });
			debug(`Created/updated SSH config: ${configPath}`);

			// Set VS Code to use our config file
			// User specified remote.antigravitySSH is the correct key
			await vscode.workspace.getConfiguration('remote.antigravitySSH').update(
				'configFile',
				configPath,
				vscode.ConfigurationTarget.Global
			);
			debug(`Set remote.antigravitySSH.configFile to: ${configPath}`);

			vscode.window.showInformationMessage(
				'SSH Config updated. Please RECONNECT to your remote server to apply changes.',
				'Reconnect'
			).then(selection => {
				if (selection === 'Reconnect') {
					vscode.commands.executeCommand('workbench.action.remote.closeConflictingBeforeConnecting');
					vscode.commands.executeCommand('workbench.action.reloadWindow');
				}
			});
		} else {
			// Clear the config file setting to revert to default
			await vscode.workspace.getConfiguration('remote.antigravitySSH').update(
				'configFile',
				undefined,
				vscode.ConfigurationTarget.Global
			);
			debug('Cleared remote.antigravitySSH.configFile setting');
		}
	} catch (error) {
		debug(`SSH config update error: ${error}`);
		throw error;
	}
}

/**
 * Check if RemoteForward is configured in our config file
 */
async function getSSHConfigStatus(): Promise<{ enabled: boolean; port?: number }> {
	try {
		const configPath = getSSHConfigAntigravityPath();
		const content = await fs.readFile(configPath, 'utf-8');
		const match = content.match(/RemoteForward\s+(\d+)\s+(?:localhost|127\.0\.0\.1):/);
		if (match) {
			return { enabled: true, port: parseInt(match[1]) };
		}
	} catch {
		// File doesn't exist or can't be read
	}
	return { enabled: false };
}

export function activate(context: vscode.ExtensionContext) {
	debugChannel = vscode.window.createOutputChannel('Antigravity Debug');
	context.subscriptions.push(debugChannel);

	debug(`Activating... isLocal=${isRunningLocally()}`);

	if (isRunningLocally()) {
		debugChannel.show(true);  // Show output channel on local/UI side
		activateLocal(context).catch(err => debug(`activateLocal error: ${err}`));
	} else {
		activateRemote(context).catch(err => debug(`activateRemote error: ${err}`));
	}
}

async function activateLocal(context: vscode.ExtensionContext) {
	const config = vscode.workspace.getConfiguration('antigravity-proxy');
	const enable = config.get<boolean>('enableLocalForwarding', true);
	const localPort = config.get<number>('localProxyPort', 7890);

	debug(`Config: enable=${enable}, port=${localPort}`);

	// Auto-setup on activation
	if (enable) {
		await updateSSHConfigFile(localPort, true);
		if (!await checkPortAvailable('127.0.0.1', localPort)) {
			vscode.window.showWarningMessage(
				`Local proxy at 127.0.0.1:${localPort} is not running. ` +
				`Also check if port ${localPort} is occupied on the remote server before reconnecting.`
			);
		}
	}

	// Watch config changes
	context.subscriptions.push(
		vscode.workspace.onDidChangeConfiguration(async (e: vscode.ConfigurationChangeEvent) => {
			if (e.affectsConfiguration('antigravity-proxy')) {
				const cfg = vscode.workspace.getConfiguration('antigravity-proxy');
				const port = cfg.get<number>('localProxyPort', 7890);
				const enabled = cfg.get<boolean>('enableLocalForwarding', true);
				await updateSSHConfigFile(port, enabled);
			}
		})
	);

	// Commands
	context.subscriptions.push(
		vscode.commands.registerCommand('antigravity-proxy.enableForwarding', async () => {
			const cfg = vscode.workspace.getConfiguration('antigravity-proxy');
			const port = cfg.get<number>('localProxyPort', 7890);
			await updateSSHConfigFile(port, true);
			vscode.window.showInformationMessage('SSH port forwarding enabled');
		}),

		vscode.commands.registerCommand('antigravity-proxy.disableForwarding', async () => {
			await updateSSHConfigFile(0, false);
			vscode.window.showInformationMessage('SSH port forwarding disabled');
		}),

		vscode.commands.registerCommand('antigravity-proxy.tunnelStatus', async () => {
			const status = await getSSHConfigStatus();
			vscode.window.showInformationMessage(
				status.enabled
					? `Forwarding configured on port: ${status.port}`
					: 'SSH port forwarding is not configured'
			);
		})
	);
}

async function activateRemote(context: vscode.ExtensionContext) {
	const config = vscode.workspace.getConfiguration('antigravity-proxy');
	const enableLocal = config.get<boolean>('enableLocalForwarding', true);
	const remoteHost = config.get<string>('remoteProxyHost', '127.0.0.1');
	const remotePort = config.get<number>('remoteProxyPort', 7890);

	const proxyHost = enableLocal ? '127.0.0.1' : remoteHost;

	debug(`Proxy: ${proxyHost}:${remotePort}`);

	// Auto-run setup script (configures environment variables, doesn't need tunnel)
	debug('Auto-running setup script...');
	await runSetupScriptSilently(proxyHost, remotePort, context.extensionPath);

	// Remote commands
	context.subscriptions.push(
		vscode.commands.registerCommand('antigravity-proxy.setup', () => {
			const terminal = vscode.window.createTerminal('Antigravity Setup');
			terminal.show();
			const script = generateSetupScript(proxyHost, remotePort, context.extensionPath);
			terminal.sendText(`cat > /tmp/ag_setup.sh << 'EOF'\n${script}\nEOF`);
			terminal.sendText('bash /tmp/ag_setup.sh');
		}),

		vscode.commands.registerCommand('antigravity-proxy.rollback', () => {
			const terminal = vscode.window.createTerminal('Antigravity Rollback');
			terminal.show();
			terminal.sendText(generateRollbackScript());
		}),

		vscode.commands.registerCommand('antigravity-proxy.checkProxy', async () => {
			const ok = await checkPortAvailable(proxyHost, remotePort);
			vscode.window.showInformationMessage(ok ? `Proxy OK` : `Proxy NOT reachable`);
		})
	);
}

/**
 * Run setup script silently in background (idempotent)
 */
async function runSetupScriptSilently(proxyHost: string, proxyPort: number, extensionPath: string): Promise<void> {
	const script = generateSetupScript(proxyHost, proxyPort, extensionPath);
	const scriptPath = '/tmp/antigravity_auto_setup.sh';

	try {
		// Use fs to write script file (heredoc in execAsync has issues)
		const fs = await import('fs/promises');
		await fs.writeFile(scriptPath, script, { mode: 0o755 });

		const { stdout, stderr } = await execAsync(`bash ${scriptPath} 2>&1`);
		const output = stdout || stderr || '';

		debug(`Setup output: ${output}`);

		if (output.includes('Already configured')) {
			debug('Setup: Already configured');
		} else if (output.includes('Setup complete') || output.includes('configured')) {
			debug('Setup: Completed successfully');
			// Don't show popup notification to avoid confusion/loops
		}
	} catch (error: unknown) {
		const err = error as { message?: string; stdout?: string; stderr?: string };
		debug(`Setup error: ${err.message || error}`);
		if (err.stdout) { debug(`stdout: ${err.stdout}`); }
		if (err.stderr) { debug(`stderr: ${err.stderr}`); }
	}
}

export function deactivate() { }

