import * as vscode from 'vscode';
import * as net from 'net';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import { generateSetupScript, generateRollbackScript } from './remoteSetup';

const execAsync = promisify(exec);

let debugChannel: vscode.OutputChannel;

function debug(message: string): void {
	const timestamp = new Date().toISOString();
	const location = isRunningLocally() ? '[LOCAL]' : '[REMOTE]';
	debugChannel?.appendLine(`${timestamp} ${location} ${message}`);
}

function isRunningLocally(): boolean {
	return !vscode.env.remoteName;
}

async function checkPortAvailable(host: string, port: number): Promise<boolean> {
	return new Promise((resolve) => {
		const socket = new net.Socket();
		socket.setTimeout(1000);
		socket.on('connect', () => { socket.destroy(); resolve(true); });
		socket.on('timeout', () => { socket.destroy(); resolve(false); });
		socket.on('error', () => { socket.destroy(); resolve(false); });
		socket.connect(port, host);
	});
}

/**
 * Get path to SSH config directory based on platform
 */
function getSSHDir(): string {
	return path.join(os.homedir(), '.ssh');
}

/**
 * Get path to our custom SSH config file
 */
function getSSHConfigAntigravityPath(): string {
	return path.join(getSSHDir(), 'config.antigravity');
}

/**
 * Get path to the original SSH config file
 */
function getSSHConfigPath(): string {
	return path.join(getSSHDir(), 'config');
}

/**
 * Read the original SSH config content
 */
async function readOriginalSSHConfig(): Promise<string> {
	try {
		const configPath = getSSHConfigPath();
		const content = await fs.readFile(configPath, 'utf-8');
		return content;
	} catch (error) {
		// If the original config doesn't exist, return empty string
		debug(`Could not read original SSH config: ${error}`);
		return '';
	}
}

/**
 * Generate the SSH config content with RemoteForward
 * The Match all rule must come BEFORE the original config content
 * to ensure it applies to all hosts
 */
function generateSSHConfigContent(remotePort: number, localPort: number, originalConfig: string): string {
	const lines = [
		'# Auto-generated by Antigravity Proxy extension',
		'# Do not edit manually - changes will be overwritten',
		`# Generated at: ${new Date().toISOString()}`,
		'',
		'# Antigravity RemoteForward rule (applies to all hosts)',
		'Match all',
		`    RemoteForward ${remotePort} 127.0.0.1:${localPort}`,
		'    ExitOnForwardFailure no',
		'    VisualHostKey no',
		'',
	];

	// Append original config content if it exists
	if (originalConfig.trim()) {
		lines.push('# ========== Original SSH Config Content ==========');
		lines.push(originalConfig);
	}

	return lines.join('\n');
}

/**
 * Update the SSH config file and VS Code settings
 */
async function updateSSHConfigFile(remotePort: number, localPort: number, enable: boolean): Promise<void> {
	const configPath = getSSHConfigAntigravityPath();

	try {
		if (enable) {
			// Ensure .ssh directory exists
			await fs.mkdir(getSSHDir(), { recursive: true });

			// Read original SSH config content
			const originalConfig = await readOriginalSSHConfig();
			debug(`Read original SSH config (${originalConfig.length} bytes)`);

			// Generate and write config content with embedded original config
			const content = generateSSHConfigContent(remotePort, localPort, originalConfig);
			await fs.writeFile(configPath, content, { encoding: 'utf-8' });
			debug(`Created/updated SSH config: ${configPath}`);

			// Set VS Code to use our config file
			await vscode.workspace.getConfiguration('remote.antigravitySSH').update(
				'configFile',
				configPath,
				vscode.ConfigurationTarget.Global
			);
			debug(`Set remote.antigravitySSH.configFile to: ${configPath}`);

			vscode.window.showInformationMessage(
				'SSH Config updated. Please RECONNECT to your remote server to apply changes.',
				'Reconnect'
			).then(selection => {
				if (selection === 'Reconnect') {
					vscode.commands.executeCommand('workbench.action.reloadWindow');
				}
			});
		} else {
			// Clear the config file setting to revert to default
			await vscode.workspace.getConfiguration('remote.antigravitySSH').update(
				'configFile',
				undefined,
				vscode.ConfigurationTarget.Global
			);
			debug('Cleared remote.antigravitySSH.configFile setting');
		}
	} catch (error) {
		debug(`SSH config update error: ${error}`);
		throw error;
	}
}

/**
 * Check if RemoteForward is configured in our config file
 */
async function getSSHConfigStatus(): Promise<{ enabled: boolean; port?: number }> {
	try {
		const configPath = getSSHConfigAntigravityPath();
		const content = await fs.readFile(configPath, 'utf-8');
		const match = content.match(/RemoteForward\s+(\d+)\s+(?:localhost|127\.0\.0\.1):/);
		if (match) {
			return { enabled: true, port: parseInt(match[1]) };
		}
	} catch {
		// File doesn't exist or can't be read
	}
	return { enabled: false };
}

export function activate(context: vscode.ExtensionContext) {
	debugChannel = vscode.window.createOutputChannel('Antigravity Debug');
	context.subscriptions.push(debugChannel);

	debug(`Activating... isLocal=${isRunningLocally()}`);

	if (isRunningLocally()) {
		debugChannel.show(true);  // Show output channel on local/UI side
		activateLocal(context).catch(err => debug(`activateLocal error: ${err}`));
	} else {
		activateRemote(context).catch(err => debug(`activateRemote error: ${err}`));
	}
}

async function activateLocal(context: vscode.ExtensionContext) {
	const config = vscode.workspace.getConfiguration('antigravity-proxy');
	const enable = config.get<boolean>('enableLocalForwarding', true);
	const localPort = config.get<number>('localProxyPort', 7890);
	const remotePort = config.get<number>('remoteProxyPort', 7890);

	debug(`Config: enable=${enable}, localPort=${localPort}, remotePort=${remotePort}`);

	// Auto-setup on activation
	if (enable) {
		await updateSSHConfigFile(remotePort, localPort, true);
		if (!await checkPortAvailable('127.0.0.1', localPort)) {
			vscode.window.showWarningMessage(
				`Local proxy at 127.0.0.1:${localPort} is not running. ` +
				`Also check if port ${remotePort} is occupied on the remote server before reconnecting.`
			);
		}
	}

	// Watch config changes
	context.subscriptions.push(
		vscode.workspace.onDidChangeConfiguration(async (e: vscode.ConfigurationChangeEvent) => {
			if (e.affectsConfiguration('antigravity-proxy')) {
				const cfg = vscode.workspace.getConfiguration('antigravity-proxy');
				const lp = cfg.get<number>('localProxyPort', 7890);
				const rp = cfg.get<number>('remoteProxyPort', 7890);
				const enabled = cfg.get<boolean>('enableLocalForwarding', true);
				await updateSSHConfigFile(rp, lp, enabled);
			}
		})
	);

	// Commands
	context.subscriptions.push(
		vscode.commands.registerCommand('antigravity-proxy.enableForwarding', async () => {
			const cfg = vscode.workspace.getConfiguration('antigravity-proxy');
			const lp = cfg.get<number>('localProxyPort', 7890);
			const rp = cfg.get<number>('remoteProxyPort', 7890);
			await updateSSHConfigFile(rp, lp, true);
			vscode.window.showInformationMessage('SSH port forwarding enabled');
		}),

		vscode.commands.registerCommand('antigravity-proxy.disableForwarding', async () => {
			await updateSSHConfigFile(0, 0, false);
			vscode.window.showInformationMessage('SSH port forwarding disabled');
		}),

		vscode.commands.registerCommand('antigravity-proxy.tunnelStatus', async () => {
			const status = await getSSHConfigStatus();
			vscode.window.showInformationMessage(
				status.enabled
					? `Forwarding configured on port: ${status.port}`
					: 'SSH port forwarding is not configured'
			);
		})
	);
}

async function activateRemote(context: vscode.ExtensionContext) {
	const config = vscode.workspace.getConfiguration('antigravity-proxy');
	// Remote only cares about remoteProxyHost and remoteProxyPort
	const remoteHost = config.get<string>('remoteProxyHost', '127.0.0.1');
	const remotePort = config.get<number>('remoteProxyPort', 7890);

	debug(`Remote Proxy: ${remoteHost}:${remotePort}`);

	// Auto-run setup script
	// Use extensionUri.fsPath for correct remote path resolution
	const extensionPath = context.extensionUri.fsPath;
	debug(`Extension path: ${extensionPath}`);
	debug('Auto-running setup script...');
	await runSetupScriptSilently(remoteHost, remotePort, extensionPath);

	// Watch config changes
	context.subscriptions.push(
		vscode.workspace.onDidChangeConfiguration(async (e: vscode.ConfigurationChangeEvent) => {
			if (e.affectsConfiguration('antigravity-proxy.remoteProxyHost') ||
				e.affectsConfiguration('antigravity-proxy.remoteProxyPort')) {
				const cfg = vscode.workspace.getConfiguration('antigravity-proxy');
				const host = cfg.get<string>('remoteProxyHost', '127.0.0.1');
				const port = cfg.get<number>('remoteProxyPort', 7890);
				debug(`Config changed, re-running setup: ${host}:${port}`);
				await runSetupScriptSilently(host, port, extensionPath);
			}
		})
	);

	// Remote commands
	context.subscriptions.push(
		vscode.commands.registerCommand('antigravity-proxy.setup', () => {
			const terminal = vscode.window.createTerminal('Antigravity Setup');
			terminal.show();
			const script = generateSetupScript(remoteHost, remotePort, extensionPath);
			terminal.sendText(`cat > /tmp/ag_setup.sh << 'EOF'\n${script}\nEOF`);
			terminal.sendText('bash /tmp/ag_setup.sh');
		}),

		vscode.commands.registerCommand('antigravity-proxy.rollback', () => {
			const terminal = vscode.window.createTerminal('Antigravity Rollback');
			terminal.show();
			terminal.sendText(generateRollbackScript());
		}),

		vscode.commands.registerCommand('antigravity-proxy.checkProxy', async () => {
			const ok = await checkPortAvailable(remoteHost, remotePort);
			vscode.window.showInformationMessage(ok ? `Proxy OK` : `Proxy NOT reachable`);
		})
	);
}

/**
 * Run setup script silently in background (idempotent)
 */
async function runSetupScriptSilently(proxyHost: string, proxyPort: number, extensionPath: string): Promise<void> {
	const scriptPath = path.join(extensionPath, 'scripts', 'setup-proxy.sh');

	try {
		// Ensure script is executable
		await execAsync(`chmod +x "${scriptPath}"`);

		// Execute script directly with environment variables for proxy config
		const env = {
			...process.env,
			PROXY_HOST: proxyHost,
			PROXY_PORT: String(proxyPort)
		};

		const { stdout, stderr } = await execAsync(`bash "${scriptPath}" 2>&1`, { env });
		const output = stdout || stderr || '';

		debug(`Setup output: ${output}`);

		if (output.includes('Already configured')) {
			debug('Setup: Already configured');
		} else if (output.includes('Setup complete') || output.includes('configured')) {
			debug('Setup: Completed successfully');
			vscode.window.showInformationMessage(
				'Antigravity Remote Setup updated. Please reload window to apply changes to the language server.',
				'Reload Window'
			).then(selection => {
				if (selection === 'Reload Window') {
					vscode.commands.executeCommand('workbench.action.reloadWindow');
				}
			});
		}
	} catch (error: unknown) {
		const err = error as { message?: string; stdout?: string; stderr?: string };
		debug(`Setup error: ${err.message || error}`);
		if (err.stdout) { debug(`stdout: ${err.stdout}`); }
		if (err.stderr) { debug(`stderr: ${err.stderr}`); }
	}
}

export function deactivate() { }

